global:
  scrape_interval: 5s #Scrape interval to every 15 seconds.
  evaluation_interval: 5s #Evaluate rules every 15 seconds.
  
scrape_configs:
  - job_name: "prometheus"
    # metrics_path defaults to '/metrics'
    static_configs:
      - targets: ["localhost:29090"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["10.5.0.1:28080"]
